module.exports = {
  bnb: "airbnb",
  bedandbreakfast: "airbnb",
  bed_and_breakfast: "airbnb",
  hostelstay: "hostel",
  hostel_stay: "hostel",
  dorm: "hostel",
  dormitory: "hostel",
  homestay: "homestay",
  home_stay: "homestay",
  guesthouse: "homestay",
  guest_house: "homestay",
  resort: "resort",
  beachresort: "resort",
  beach_resort: "resort",
  hotel: "hotel",
  lodge: "hotel",
  inn: "hotel",
};
