module.exports = [
  "goa", "kerala", "meghalaya", "himachal", "manali", "shimla", "darjeeling",
  "sikkim", "assam", "rajasthan", "jaipur", "udaipur", "jaisalmer", "agra",
  "delhi", "mumbai", "bengaluru", "bangalore", "chennai", "kolkata",
  "hyderabad", "pune", "ahmedabad", "kashmir", "ladakh", "leh",
  "andaman", "lakshadweep", "coorg", "ooty", "munnar", "alleppey", "varkala",
  "pondicherry", "rishikesh", "varanasi", "amritsar", "khajuraho",
  "hampi", "badami", "ellora", "ajanta", "mahabalipuram", "konark",
  "puri", "gangtok", "pelling", "tawang", "shillong", "cherrapunji",
  "spiti", "dharamshala", "mcleodganj", "nainital", "mussoorie",
  "paris", "london", "tokyo", "dubai", "singapore", "bangkok", "phuket",
  "bali", "maldives", "switzerland", "thailand", "vietnam", "cambodia",
  "nepal", "bhutan", "sri lanka", "usa", "new york", "los angeles",
  "san francisco", "chicago", "australia", "sydney", "melbourne",
  "europe", "italy", "rome", "venice", "france", "spain", "barcelona",
  "germany", "berlin", "netherlands", "amsterdam", "greece", "santorini",
  "egypt", "turkey", "istanbul", "south africa", "morocco", "kenya",
  "tanzania", "malaysia", "kuala lumpur", "indonesia", "japan", "kyoto",
  "osaka", "south korea", "seoul", "china", "hong kong", "taiwan",
  "taipei", "philippines", "manila", "cebu", "mexico", "cancun",
  "canada", "toronto", "vancouver", "brazil", "rio de janeiro",
  "new zealand", "queenstown", "iceland", "norway", "sweden",
];
