module.exports = {
  veg: "vegetarian",
  vegetarian: "vegetarian",
  vegan: "vegan",
  plantbased: "vegan",
  plant_based: "vegan",
  nonveg: "non-vegetarian",
  "non-veg": "non-vegetarian",
  nonvegetarian: "non-vegetarian",
  meat: "non-vegetarian",
  streetfood: "local street food",
  street_food: "local street food",
  localstreetfood: "local street food",
  localfood: "local cuisine",
  local_food: "local cuisine",
  regional: "local cuisine",
  finedining: "fine dining",
  fine_dining: "fine dining",
  gourmet: "fine dining",
};
